apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rest-json-quickstart-quarkus
    app.kubernetes.io/instance: rest-json-quickstart-quarkus
  name: rest-json-quickstart-quarkus
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-json-quickstart-quarkus
status:
  loadBalancer: {}